import { Movie, Clip } from '../types';

export const MOCK_MOVIES: Movie[] = [
    {
        id: '1',
        title: 'Inception',
        description: 'A thief who steals corporate secrets through dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.',
        genre: 'Sci-Fi',
        thumbnailUrl: 'https://picsum.photos/seed/inception/300/450',
        heroUrl: 'https://picsum.photos/seed/inception-hero/800/450',
        clips: [
            { id: 'c1', movieId: '1', videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4', sequence: 1, duration: 60 },
            { id: 'c2', movieId: '1', videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4', sequence: 2, duration: 60 },
        ],
    },
    {
        id: '2',
        title: 'The Dark Knight',
        description: 'When the menace known as the Joker wreaks havoc on Gotham, Batman must accept one of the greatest tests to fight injustice.',
        genre: 'Action',
        thumbnailUrl: 'https://picsum.photos/seed/darkknight/300/450',
        heroUrl: 'https://picsum.photos/seed/darkknight-hero/800/450',
        clips: [
            { id: 'c3', movieId: '2', videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4', sequence: 1, duration: 45 },
        ],
    },
    {
        id: '3',
        title: 'Interstellar',
        description: 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival.',
        genre: 'Sci-Fi',
        thumbnailUrl: 'https://picsum.photos/seed/interstellar/300/450',
        heroUrl: 'https://picsum.photos/seed/interstellar-hero/800/450',
        clips: [
            { id: 'c4', movieId: '3', videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4', sequence: 1, duration: 90 },
        ],
    },
    {
        id: '4',
        title: 'The Matrix',
        description: 'A computer programmer discovers that reality as he knows it is a simulation and joins a rebellion to break free.',
        genre: 'Sci-Fi',
        thumbnailUrl: 'https://picsum.photos/seed/matrix/300/450',
        heroUrl: 'https://picsum.photos/seed/matrix-hero/800/450',
        clips: [],
    },
    {
        id: '5',
        title: 'Pulp Fiction',
        description: 'The lives of two mob hitmen, a boxer, a gangster and his wife intertwine in four tales of violence and redemption.',
        genre: 'Drama',
        thumbnailUrl: 'https://picsum.photos/seed/pulpfiction/300/450',
        heroUrl: 'https://picsum.photos/seed/pulpfiction-hero/800/450',
        clips: [],
    },
    {
        id: '6',
        title: 'Avengers: Endgame',
        description: 'After the devastating events of Infinity War, the Avengers assemble once more to undo Thanos actions and restore balance.',
        genre: 'Action',
        thumbnailUrl: 'https://picsum.photos/seed/endgame/300/450',
        heroUrl: 'https://picsum.photos/seed/endgame-hero/800/450',
        clips: [],
    },
    {
        id: '7',
        title: 'Parasite',
        description: 'Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.',
        genre: 'Thriller',
        thumbnailUrl: 'https://picsum.photos/seed/parasite/300/450',
        heroUrl: 'https://picsum.photos/seed/parasite-hero/800/450',
        clips: [],
    },
    {
        id: '8',
        title: 'Joker',
        description: 'A mentally troubled stand-up comedian embarks on a downward spiral that leads to the creation of an iconic villain.',
        genre: 'Drama',
        thumbnailUrl: 'https://picsum.photos/seed/joker/300/450',
        heroUrl: 'https://picsum.photos/seed/joker-hero/800/450',
        clips: [],
    },
    {
        id: '9',
        title: 'Spider-Man: No Way Home',
        description: 'Peter Parker seeks help from Doctor Strange when his identity is revealed, causing the multiverse to collapse.',
        genre: 'Action',
        thumbnailUrl: 'https://picsum.photos/seed/spiderman/300/450',
        heroUrl: 'https://picsum.photos/seed/spiderman-hero/800/450',
        clips: [],
    },
    {
        id: '10',
        title: 'Dune',
        description: 'Paul Atreides, a young man born into a great destiny, must travel to the most dangerous planet in the universe.',
        genre: 'Sci-Fi',
        thumbnailUrl: 'https://picsum.photos/seed/dune/300/450',
        heroUrl: 'https://picsum.photos/seed/dune-hero/800/450',
        clips: [],
    },
    {
        id: '11',
        title: 'The Godfather',
        description: 'The aging patriarch of an organized crime dynasty transfers control to his reluctant son.',
        genre: 'Drama',
        thumbnailUrl: 'https://picsum.photos/seed/godfather/300/450',
        heroUrl: 'https://picsum.photos/seed/godfather-hero/800/450',
        clips: [],
    },
    {
        id: '12',
        title: 'Fight Club',
        description: 'An insomniac office worker and a soap salesman build a global organization to help vent male aggression.',
        genre: 'Drama',
        thumbnailUrl: 'https://picsum.photos/seed/fightclub/300/450',
        heroUrl: 'https://picsum.photos/seed/fightclub-hero/800/450',
        clips: [],
    },
    {
        id: '13',
        title: 'Forrest Gump',
        description: 'The presidencies of Kennedy and Johnson unfold through the perspective of an Alabama man with an IQ of 75.',
        genre: 'Drama',
        thumbnailUrl: 'https://picsum.photos/seed/forrestgump/300/450',
        heroUrl: 'https://picsum.photos/seed/forrestgump-hero/800/450',
        clips: [],
    },
    {
        id: '14',
        title: 'The Shawshank Redemption',
        description: 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.',
        genre: 'Drama',
        thumbnailUrl: 'https://picsum.photos/seed/shawshank/300/450',
        heroUrl: 'https://picsum.photos/seed/shawshank-hero/800/450',
        clips: [],
    },
    {
        id: '15',
        title: 'Gladiator',
        description: 'A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family.',
        genre: 'Action',
        thumbnailUrl: 'https://picsum.photos/seed/gladiator/300/450',
        heroUrl: 'https://picsum.photos/seed/gladiator-hero/800/450',
        clips: [],
    },
    {
        id: '16',
        title: 'The Lion King',
        description: 'Lion prince Simba flees after the death of his father and returns as an adult to reclaim his throne.',
        genre: 'Animation',
        thumbnailUrl: 'https://picsum.photos/seed/lionking/300/450',
        heroUrl: 'https://picsum.photos/seed/lionking-hero/800/450',
        clips: [],
    },
    {
        id: '17',
        title: 'Titanic',
        description: 'A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious Titanic.',
        genre: 'Romance',
        thumbnailUrl: 'https://picsum.photos/seed/titanic/300/450',
        heroUrl: 'https://picsum.photos/seed/titanic-hero/800/450',
        clips: [],
    },
    {
        id: '18',
        title: 'Avatar',
        description: 'A paraplegic Marine dispatched to Pandora becomes torn between following his orders and protecting the world he calls home.',
        genre: 'Sci-Fi',
        thumbnailUrl: 'https://picsum.photos/seed/avatar/300/450',
        heroUrl: 'https://picsum.photos/seed/avatar-hero/800/450',
        clips: [],
    },
    {
        id: '19',
        title: 'The Prestige',
        description: 'Two stage magicians engage in a bitter rivalry, each trying to discover the secret of the others tricks.',
        genre: 'Thriller',
        thumbnailUrl: 'https://picsum.photos/seed/prestige/300/450',
        heroUrl: 'https://picsum.photos/seed/prestige-hero/800/450',
        clips: [],
    },
    {
        id: '20',
        title: 'Django Unchained',
        description: 'A freed slave sets out to rescue his wife from a brutal plantation owner with the help of a German bounty hunter.',
        genre: 'Action',
        thumbnailUrl: 'https://picsum.photos/seed/django/300/450',
        heroUrl: 'https://picsum.photos/seed/django-hero/800/450',
        clips: [],
    },
    {
        id: '21',
        title: 'The Social Network',
        description: 'The story of the founding of Facebook and the lawsuits that followed its meteoric rise.',
        genre: 'Drama',
        thumbnailUrl: 'https://picsum.photos/seed/socialnetwork/300/450',
        heroUrl: 'https://picsum.photos/seed/socialnetwork-hero/800/450',
        clips: [],
    },
    {
        id: '22',
        title: 'Mad Max: Fury Road',
        description: 'In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler with the help of a drifter.',
        genre: 'Action',
        thumbnailUrl: 'https://picsum.photos/seed/madmax/300/450',
        heroUrl: 'https://picsum.photos/seed/madmax-hero/800/450',
        clips: [],
    },
    {
        id: '23',
        title: 'Whiplash',
        description: 'A promising young drummer enrolls at a cutthroat music conservatory where his dreams of greatness are mentored by an abusive instructor.',
        genre: 'Drama',
        thumbnailUrl: 'https://picsum.photos/seed/whiplash/300/450',
        heroUrl: 'https://picsum.photos/seed/whiplash-hero/800/450',
        clips: [],
    },
    {
        id: '24',
        title: 'Get Out',
        description: 'A young African-American visits his white girlfriends parents and uncovers a disturbing secret.',
        genre: 'Horror',
        thumbnailUrl: 'https://picsum.photos/seed/getout/300/450',
        heroUrl: 'https://picsum.photos/seed/getout-hero/800/450',
        clips: [],
    },
    {
        id: '25',
        title: 'La La Land',
        description: 'A jazz musician and an aspiring actress fall in love while pursuing their dreams in Los Angeles.',
        genre: 'Romance',
        thumbnailUrl: 'https://picsum.photos/seed/lalaland/300/450',
        heroUrl: 'https://picsum.photos/seed/lalaland-hero/800/450',
        clips: [],
    },
];
